---
# ci_cd/Ansible/configure_storageclass.yml
- hosts: "{{ master_ip }}, "
  become: true
  tasks:
    - name: Скопировать kubeconfig на контроллер Jenkins
      fetch:
        src: /home/moon/.kube/config
        dest: /tmp/kubeconfig
        flat: yes
      when: kubeconfig_file.stat.exists

    - name: Скопировать kubeconfig на контроллер Jenkins
      fetch:
        src: /home/moon/.kube/config
        dest: /tmp/kubeconfig
        flat: yes
      when: kubeconfig_file.stat.exists
# Storage
    - name: Установить StorageClass для локального пути
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
      environment:
        KUBECONFIG: /home/moon/.kube/config

    - name: Сделать local-path StorageClass классом по умолчанию
      shell: |
        kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      environment:
        KUBECONFIG: /home/moon/.kube/config

    - name: Включить планирование на всех узлах
      shell: kubectl uncordon $(kubectl get nodes --no-headers -o custom-columns=":metadata.name")
      environment:
        KUBECONFIG: /home/moon/.kube/config
      register: uncordon_result

    - name: Печать результата uncordon
      debug:
        msg: "{{ uncordon_result.stdout }}"