all:
  hosts:
    node1:
      ansible_host: 228
      ip: 228
      access_ip: 228
    node2:
      ansible_host: 322
      ip: 322
      access_ip: 322
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
