---
# ci_cd/Ansible/kubespray_setup.yml
- hosts: localhost
  #become: true
  tasks:
    - name: Debugging variables
      debug:
        var: ansible_user

    - name: Клонировать репозиторий Kubespray на Jenkins воркере
      git:
        repo: 'https://github.com/kubernetes-sigs/kubespray.git'
        dest: "{{ lookup('env', 'WORKSPACE') }}/kubespray"
        version: master
        update: yes
        track_submodules: yes
        accept_hostkey: yes

    #- name: Проверить права доступа на директорию
    #  command: ls -ld "{{ lookup('env', 'WORKSPACE') }}/kubespray"

    #- name: Установить зависимости на Jenkins воркере
    #  become: true
    #  apt:
    #    name:
    #      - python3-pip
    #      - python3-setuptools
    #      - python3-venv
    #      - python3-wheel
    #    state: present
    #    update_cache: yes

    - name: Установить зависимости pip
      #become: true
      pip:
        requirements: "{{ lookup('env', 'WORKSPACE') }}/kubespray/requirements.txt"

    - name: Копировать инвентарь и настроить под ВМ
      shell: |
        cd "{{ lookup('env', 'WORKSPACE') }}/kubespray"
        cp -rfp inventory/sample inventory/mycluster
        CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py {{ master_ip }} {{ worker_ip }}
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}/kubespray"

    - name: Запустить настройку кластера Kubernetes
      shell: |
        cd "{{ lookup('env', 'WORKSPACE') }}/kubespray"
        ansible-playbook -i inventory/mycluster/hosts.yml --private-key $SSH_KEY --become --become-user=$SSH_USER cluster.yml
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}/kubespray"