---
# ci_cd/Ansible/kubespray_setup.yml
- hosts: localhost
  become: true
  tasks:
    - name: Клонировать репозиторий Kubespray на Jenkins воркере
      git:
        repo: 'https://github.com/kubernetes-sigs/kubespray.git'
        dest: /home/jenkins/kubespray

    - name: Установить зависимости на Jenkins воркере
      become: true
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-venv
          - python3-wheel
        state: present
        update_cache: yes

    - name: Установить зависимости pip
      pip:
        requirements: /home/jenkins/kubespray/requirements.txt

    - name: Копировать инвентарь и настроить под ВМ
      shell: |
        cd /home/jenkins/kubespray
        cp -rfp inventory/sample inventory/mycluster
        CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py {{ master_ip }} {{ worker_ip }}
      args:
        chdir: /home/jenkins/kubespray

    - name: Запустить настройку кластера Kubernetes
      shell: |
        cd /home/jenkins/kubespray
        ansible-playbook -i inventory/mycluster/hosts.yml --private-key /path/to/your/private/key --become --become-user=$SSH_USER cluster.yml
      args:
        chdir: /home/jenkins/kubespray
