---
# ci_cd/Ansible/kubespray_setup.yml
- hosts: localhost
  tasks:
    - name: Debugging variables
      debug:
        var: ansible_user

    - name: Клонировать репозиторий Kubespray на Jenkins воркере
      git:
        repo: 'https://github.com/kubernetes-sigs/kubespray.git'
        dest: "{{ lookup('env', 'WORKSPACE') }}/kubespray"

    - name: Установить зависимости pip
      pip:
        requirements: "{{ lookup('env', 'WORKSPACE') }}/kubespray/requirements.txt"

    - name: Установить ruamel.yaml
      pip:
        name: ruamel.yaml

    - name: Копировать инвентарь и настроить под ВМ
      shell: |
        cd "{{ lookup('env', 'WORKSPACE') }}/kubespray"
        cp -rfp inventory/sample inventory/mycluster
        CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py {{ master_ip }} {{ worker_ip }}
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}/kubespray"

    - name: Запустить настройку кластера Kubernetes
      shell: |
        cd "{{ lookup('env', 'WORKSPACE') }}/kubespray"
        ansible-playbook -i inventory/mycluster/hosts.yml -e ansible_ssh_private_key_file=${VM_SSH_KEY} -b -u ${VM_SSH_USER} cluster.yml
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}/kubespray"