---
# ci_cd/Ansible/kubespray_setup.yml
- hosts: all
  become: true
  tasks:
    - name: Клонировать репозиторий Kubespray
      git:
        repo: 'https://github.com/kubernetes-sigs/kubespray.git'
        dest: /home/moon/kubespray

    - name: Установить зависимости для Kubespray
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-venv
          - python3-wheel
        state: present
        update_cache: yes

    - name: Установить зависимости pip
      pip:
        requirements: /home/moon/kubespray/requirements.txt

    - name: Установить ruamel.yaml
      pip:
        name: ruamel.yaml

    - name: Копировать приватный ключ на мастер
      copy:
        src: /home/jenkins/.ssh/id_rsa
        dest: /home/moon/.ssh/id_rsa
        mode: '0600'

    - name: Копировать инвентарь и настроить под ВМ
      shell: |
        cd /home/moon/kubespray
        cp -rfp inventory/sample inventory/mycluster
        CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py {{ master_ip }} {{ worker_ip }}
      args:
        chdir: /home/moon/kubespray

    - name: Запустить настройку кластера Kubernetes
      shell: |
        cd /home/moon/kubespray
        ansible-playbook -i inventory/mycluster/hosts.yml --private-key ~/.ssh/id_rsa --become --become-user=root cluster.yml
      args:
        chdir: /home/moon/kubespray

    - name: Установить StorageClass для локального пути
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
      environment:
        KUBECONFIG: /home/moon/.kube/config

    - name: Сделать local-path StorageClass классом по умолчанию
      shell: |
        kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      environment:
        KUBECONFIG: /home/moon/.kube/config

    - name: Проверить, существует ли kubeconfig
      stat:
        path: /home/moon/.kube/config
      register: kubeconfig_file

    - name: Создать kubeconfig из admin.conf, если не существует
      shell: |
        mkdir -p /home/moon/.kube
        cp /etc/kubernetes/admin.conf /home/moon/.kube/config
      when: not kubeconfig_file.stat.exists

    - name: Скопировать kubeconfig на контроллер Jenkins
      fetch:
        src: /home/moon/.kube/config
        dest: /tmp/kubeconfig
        flat: yes
      when: kubeconfig_file.stat.exists

    - name: Включить планирование на всех узлах
      shell: kubectl uncordon $(kubectl get nodes --no-headers -o custom-columns=":metadata.name")
      environment:
        KUBECONFIG: /home/moon/.kube/config
      register: uncordon_result

    - name: Печать результата uncordon
      debug:
        msg: "{{ uncordon_result.stdout }}"