---
# ci_cd/Ansible/kubespray_setup.yml
- hosts: {{ master_ip }}
  tasks:
# Зависимости, пакетыё
    - name: Клонировать репозиторий Kubespray на Jenkins воркере
      git:
        repo: 'https://github.com/kubernetes-sigs/kubespray.git'
        dest: "{{ lookup('env', 'WORKSPACE') }}/kubespray"

    - name: Установить зависимости pip
      pip:
        requirements: "{{ lookup('env', 'WORKSPACE') }}/kubespray/requirements.txt"

    - name: Установить ruamel.yaml
      pip:
        name: ruamel.yaml

# Инвентарь + Плейбук кластера
    #- name: Копировать инвентарь и настроить под ВМ
    #  shell: |
    #    cd "{{ lookup('env', 'WORKSPACE') }}/kubespray"
    #    cp -rfp inventory/sample inventory/mycluster
    #    CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py {{ master_ip }} {{ worker_ip }}
    #  args:
    #    chdir: "{{ lookup('env', 'WORKSPACE') }}/kubespray"

    #- name: Запустить настройку кластера Kubernetes
    #  shell: |
    #    cd "{{ lookup('env', 'WORKSPACE') }}/kubespray"
    #    ansible-playbook -i inventory/mycluster/hosts.yml -e ansible_ssh_private_key_file=${VM_SSH_KEY} -b -u ${VM_SSH_USER} cluster.yml
    #  args:
    #    chdir: "{{ lookup('env', 'WORKSPACE') }}/kubespray"


# После кластера
#    - name: Скопировать kubeconfig на контроллер Jenkins
#      fetch:
#        src: /home/moon/.kube/config
#        dest: /tmp/kubeconfig
#        flat: yes
#      when: kubeconfig_file.stat.exists

## Storage
#    - name: Установить StorageClass для локального пути
#      shell: |
#        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
#      environment:
#        KUBECONFIG: /home/moon/.kube/config

#    - name: Сделать local-path StorageClass классом по умолчанию + включить планирование
#      shell: |
#        kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
#        kubectl uncordon $(kubectl get nodes --no-headers -o custom-columns=":metadata.name")
#      environment:
#        KUBECONFIG: /home/moon/.kube/config