---
- hosts: all
  become: true
  tasks:
    - name: Проврка
      shell: hostname && pwd && whoami

    - name: Update package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Fix broken dependencies
      apt:
        upgrade: yes
        autoclean: yes
        autoremove: yes

    - name: Установить Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Убедиться, что Docker включен
      systemd:
        name: docker
        enabled: yes
        state: started