# Generated by Django 4.2 on 2024-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
