# Generated by Django 4.2 on 2024-07-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
