# Generated by Django 4.2 on 2024-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="first_name",
            field=models.CharField(default="empty", max_length=100),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="last_name",
            field=models.CharField(default="empty", max_length=100),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="patronymic",
            field=models.CharField(default="empty", max_length=100),
        ),
    ]
