# Generated by Django 4.2 on 2024-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_alter_doctorprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="email",
            field=models.EmailField(default="mail@mail.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(default="no_spec", max_length=100),
        ),
    ]
