#!/bin/bash

NAME="Emais"
DJANGODIR=/home/kirill/Desktop/практика2024/emais_prct2024/Emais
#SOCKFILE=/home/kirill/Desktop/практика2024/emais_prct2024/Emais/gunicorn_start
SOCKFILE=/home/kirill/Desktop/практика2024/emais_prct2024/Emais/gunicorn.sock
USER=kirill
GROUP=kirill
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=Emais.settings
#DJANGO_SETTINGS_MODULE=/home/kirill/Desktop/практика2024/emais_prct2024/Emais/Emais/settings.py
DJANGO_WSGI_MODULE=Emais.wsgi 
#DJANGO_WSGI_MODULE=/home/kirill/Desktop/практика2024/emais_prct2024/Emais/Emais/wsgi.py

echo "Starting $NAME as `whoami`"

cd $DJANGODIR
source /home/kirill/Desktop/практика2024/emais_prct2024/venv
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec /home/kirill/Desktop/практика2024/emais_prct2024/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
