# Generated by Django 4.2 on 2024-07-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_patientprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
