# Generated by Django 4.2 on 2024-07-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0007_alter_medicalrecord_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="images",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
