# Generated by Django 4.2 on 2024-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0008_remove_medicalrecord_images_medicalrecord_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="medical_records/"
            ),
        ),
    ]
