# Generated by Django 4.2 on 2024-07-19 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0009_alter_medicalrecord_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patient.appointment",
            ),
        ),
    ]
