# Generated by Django 4.2 on 2024-07-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
        ("patient", "0010_alter_medicalrecord_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctor.doctorprofile",
            ),
        ),
        migrations.DeleteModel(
            name="PatientMyInfo",
        ),
    ]
