# Generated by Django 4.2 on 2024-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0014_remove_medicalrecord_image_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="image_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="MedicalRecordImage",
        ),
    ]
